stages:
  - package-app
  - build-image

variables:
  GIT_DEPTH: "0"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DskipTests -Dquarkus.package.type=fast-jar"
  POM_FILE: ./pom.xml

package-quarkus:
  stage: package-app
  image: eclipse-temurin:17-jdk-alpine
  script:
    - ./mvnw clean package $MAVEN_OPTS $MAVEN_CLI_OPTS
    - ls -R target
  artifacts:
    paths:
      - target/quarkus-app/
      - target/*-runner.jar

build-quarkus-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/src/main/docker/Dockerfile.jvm"
      --destination "${CI_REGISTRY}/cs3/rnd/nebulous/security-layer:latest"
