version: '3.8'

services:
#  activemq-artemis:
#    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.21
#    environment:
#      AMQ_USER: quarkus
#      AMQ_PASSWORD: quarkus
#      AMQ_EXTRA_ARGS: "--host 0.0.0.0 --http-host 0.0.0.0 --relax-jolokia"
#    ports:
#      - "8161:8161"   # Web Server
#      - "61616:61616" # Core,MQTT,AMQP,HORNETQ,STOMP,Openwire
#      - "5672:5672"   # AMQP
#    restart: unless-stopped
#


  activemq:
    image: rmohr/activemq:latest
    environment:
      ACTIVEMQ_ADMIN_LOGIN: quarkus
      ACTIVEMQ_ADMIN_PASSWORD: quarkus
      ACTIVEMQ_USER_LOGIN: quarkus
      ACTIVEMQ_USER_PASSWORD: quarkus
    ports:
      - "8161:8161"   # Web Console
      - "61616:61616" # JMS
      - "5672:5672"   # AMQP
      - "61613:61613" # STOMP
      - "1883:1883"   # MQTT
      - "61614:61614" # WS
    restart: unless-stopped


